pipeline:
  name: gh-pipeline
  identifier: ghpipeline
  projectIdentifier: karantest
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: wait
        identifier: wait
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Wait
                  name: Wait_1
                  identifier: Wait_1
                  spec:
                    duration: 10m
        tags: {}
