pipeline:
  name: github test
  identifier: github_test
  projectIdentifier: karan_test
  orgIdentifier: NgTriggersOrg
  tags: {}
  stages:
    - stage:
        name: asd
        identifier: asd
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo 1
                    environmentVariables: []
                    outputVariables: []
                  timeout: <+input>
        tags: {}
