pipeline:
  name: github test
  identifier: github_test
  projectIdentifier: karan_test
  orgIdentifier: NgTriggersOrg
  tags: {}
  stages:
    - stage:
        name: asd
        identifier: asd
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo 1
                    environmentVariables: []
                    outputVariables: []
                  timeout: <+input>
        tags: {}
    - stage:
        name: inline
        identifier: inline
        tags: {}
        template:
          templateRef: account.stageTempTestAccLevelEnv
          versionLabel: v1
          templateInputs:
            type: Deployment
            spec:
              service:
                serviceRef: <+input>
                serviceInputs: <+input>
    - stage:
        name: remote
        identifier: remote
        tags: {}
        template:
          templateRef: account.stage_a2_tempalte
          versionLabel: v23
          gitBranch: main
