pipeline:
  name: hgcfyg
  identifier: hgcfyg
  projectIdentifier: karan_test
  orgIdentifier: NgTriggersOrg
  tags: {}
  stages:
    - stage:
        name: custom
        identifier: custom
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo 100
                    environmentVariables: []
                    outputVariables: []
                  timeout: <+input>
        tags: {}
    - stage:
        name: LKJNLKJ
        identifier: LKJNLKJ
        tags: {}
        template:
          templateRef: account.stage_a2_tempalte
          versionLabel: v23
