---
pipeline:
  projectIdentifier: "karan_test"
  orgIdentifier: "NgTriggersOrg"
  tags: {}
  stages:
  - stage:
      name: "test"
      identifier: "test"
      description: ""
      type: "Custom"
      spec:
        execution:
          steps:
          - step:
              type: "ShellScript"
              name: "ShellScript_1"
              identifier: "ShellScript_1"
              spec:
                shell: "Bash"
                executionTarget: {}
                source:
                  type: "Inline"
                  spec:
                    script: "echo 1"
                environmentVariables: []
                outputVariables: []
              timeout: "<+input>"
      tags: {}
  - stage:
      name: "build"
      identifier: "build"
      description: ""
      type: "CI"
      spec:
        cloneCodebase: true
        platform:
          os: "Linux"
          arch: "Amd64"
        runtime:
          type: "Cloud"
          spec: {}
        execution:
          steps:
          - step:
              type: "Run"
              name: "Run_1"
              identifier: "Run_1"
              spec:
                shell: "Sh"
                command: "echo 2"
  properties:
    ci:
      codebase:
        repoName: "<+input>"
        build: "<+input>"
  identifier: "test_inline_Clone"
  name: "test inline - Clone"
