pipeline:
  projectIdentifier: testkaran
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: custom
        identifier: custom
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo 10
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
  identifier: gh_remote_pipeline_delegate
  name: gh remote pipeline - delegate
